import { GameStoreState } from './types';
import { INITIAL_GAME_STATE } from '../constants';
import { View } from '../types';

export const initialState: GameStoreState = {
  loading: true,
  loadingProgress: 0,
  loadingMessage: 'Mempersiapkan...',
  loadingError: null,
  isProcessing: false,
  sessionProgress: null,
  isSessionProcessingComplete: false,
  gameState: INITIAL_GAME_STATE,
  talents: [],
  guests: [],
  gachaTalentPool: [],
  selectedTalent: null,
  selectedRoomId: null,
  viewingTalent: null,
  viewingGuest: null,
  viewingReceipt: null,
  matchResult: null,
  endDayResult: null,
  gachaResult: null,
  equipmentGachaResult: null,
  activeView: View.MAIN_MENU,
  cleaningTimers: {},
  viewingPhoneInventoryFor: null,
  viewingEquipmentInventoryFor: null,
  livestreamResult: null,
  activeLivestreamSession: null,
  livestreamSetup: null,
  productionSetup: null,
  productionResult: null,
  originalMoney: null,
  originalTalentEarnings: null,
  viewingOutcallFor: null,
  activeRaidEvent: null,
  activeSatpolPpEvent: null,
  activePoliceRaidEvent: null,
};
